<table border="1" cellspacing="1" cellpadding="0">

    <tr>
        <td><table width="100%" border="0" cellspacing="1" cellpadding="0">

                <?php
                $referencia = "";
                $orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
                $quote_id = Mage::getSingleton('checkout/session')->getQuoteId();
                $conn = Mage::getSingleton('core/resource')->getConnection('core_read');

                if ($quote_id != "") {
                    
                    $sales_flat_quote_payment = Mage::getSingleton('core/resource')->getTableName('sales_flat_quote_payment');
                    $query = $conn->query("SELECT  eupago_referencia FROM $sales_flat_quote_payment  WHERE quote_id= $quote_id");
                    $referencia = $query->fetchColumn();
                }
                if ($referencia == "") {
                    ?>
                    <tr>
                        <td><img src="<?php echo $this->getSkinUrl('images/multibanco/eupagomultibanco.png') ?>" border="0" alt="<?php echo $this->getMethod()->getTitle(); ?>" title="<?php echo $this->getMethod()->getTitle(); ?>" /></td>
                    </tr>
                    <tr>
                        <td>  Os dados para pagamento multibanco ser&atilde;o apresentados quando finalizar a sua encomenda e/ou enviados para o seu e-mail.</td></tr>
<?
} else {


    $conn = Mage::getSingleton('core/resource')->getConnection('core_read');
      $sales_flat_order_payment = Mage::getSingleton('core/resource')->getTableName('sales_flat_order_payment');
    $query = $conn->query("SELECT  max(parent_id) eupago_referencia FROM  $sales_flat_order_payment ");
    $entity_id = $query->fetchColumn();



    $query = $conn->query("SELECT  eupago_referencia FROM $sales_flat_order_payment  WHERE parent_id=$entity_id");
    $referencia = $query->fetchColumn();
    $query = $conn->query("SELECT  eupago_entidade FROM $sales_flat_order_payment  WHERE parent_id=$entity_id");
    $entidade = $query->fetchColumn();
    $query = $conn->query("SELECT  eupago_montante FROM $sales_flat_order_payment  WHERE parent_id=$entity_id");
    $valor = $query->fetchColumn();
     $valor = number_format($valor,'2',',','');
    ?>

                    <div align='center'>





                        <table style="margin-top: 10px;border: 1px solid #000;" width="250px" cellspacing="0" align="center">
                            <tr>
                                 <td colspan="2" style="height:25px;vertical-align:center; text-align:center">
                                    <img src="https://seguro.eupago.pt/repositorio/imagens/eupagomultibanco.png" alt="euPago Multibanco" height="25" />
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" style="height:25px;vertical-align:center;background-color:#3a87ad;font-size:small;text-align:center;color:#ebebeb;">
                                    Multibanco (Pagamento de Compras\Servi&ccedil;os)</td>
                            </tr>
                            <tr>
                                <td align="left" style="font-size:small;font-weight:bold;padding-left:15px;">Entidade:</td>
                                <td align="left" style="font-size:small;"><?php echo $entidade; ?></td>
                            </tr>
                            <tr>
                                <td align="left" style="font-size:small;font-weight:bold;padding-left:15px;">Refer&ecirc;ncia:</td>
                                <td align="left" style="font-size:small;"><?php echo $referencia; ?> </td>
                            </tr>
                            <tr>
                                <td align="left" style="font-size:small;font-weight:bold;padding-left:15px;">Valor:</td>
                                <td align="left" style="font-size:small;"><?php echo $valor; ?>EUR </td>
                            </tr>

                        </table>

                    </div>   




<? } ?>
    </tr>

</table></td>
</tr>
</table>