<ul id="payment_info_<?php echo $this->getMethodCode() ?>">
    <li style="min-width: 300px;">
	<h4>Multibanco</h4>
	<?php 
	$multibanco_data = $this->getMultibancoData(); 
	if(isset($multibanco_data->referencia) && $multibanco_data->referencia != ""){
		echo $this->__('Entidade: ').$multibanco_data->entidade."</br>" 
			.$this->__('Referência: ').chunk_split($multibanco_data->referencia,3," ")."</br>"
			.$this->__('Valor: ').number_format($multibanco_data->valor,2)." EUR"; 
	}else
		echo $this->__('Vai receber nos seus dispositivos inscritos no MB WAY um pedido de pagamento. Para validar a compra basta aceitar e introduzir o seu PIN MB WAY.') ?>
    </li>
</ul>