<ul id="payment_info_<?php echo $this->getMethodCode() ?>">
    <li style="min-width: 400px;">
	<?php 
	$multibanco_data = $this->getMultibancoData(); 
	if(isset($multibanco_data->referencia) && $multibanco_data->referencia != ""){?>
		<div align='center'>
			<table style="width:100%; padding:5px; font-size: 11px; color: #374953; margin:0 auto;">
				<tbody>
					<tr>
						<td style="font-size: 12px; border-top: 0px; border-left: 0px; border-right: 0px; border-bottom: 1px solid #45829F; padding:3px; background-color: #45829F; color: White; height:25px; line-height:25px" colspan="3"><div align="center"><?php echo $this->__('Pagamento por Multibanco ou Homebanking') ?></div></td>
					</tr>
					<tr style="background-color:#f1f1f1;">
						<td style="padding:8px 0;" rowspan="3"><div align="center"><img src="<?php echo $this->getSkinUrl('images/eupago/multibanco/eupago_mb_p.png'); ?>" alt="euPago" /></div></td>
						<td style="padding:10px 2px 2px 2px; font-weight:bold; text-align:left"><?php echo $this->__('Entidade') ?></td>
						<td style="padding:10px 2px 2px 2px;  text-align:left"><?php echo $multibanco_data->entidade; ?></td>
					</tr>
					<tr style="background-color:#f1f1f1;">
						<td style=" padding:2px; font-weight:bold; text-align:left"><?php echo $this->__('Referência') ?></td>
						<td style=" padding:2px; text-align:left"><?php echo chunk_split($multibanco_data->referencia,3,' '); ?></td>
					</tr>
					<tr style="background-color:#f1f1f1;">
						<td style="padding:2px; padding-bottom:10px; font-weight:bold; text-align:left"><?php echo $this->__('Valor') ?></td>
						<td style="padding:2px; padding-bottom:10px; text-align:left"><?php echo number_format($multibanco_data->valor,2).' EUR'; ?></td>
					</tr>
					<tr>
						<td style="font-size: xx-small; padding:0; border: 0px; text-align:center;" colspan="3"><?php echo $this->__('O ticket obtido na maquina automática faz prova de pagamento.') ?></td>
					</tr>
					<?php if(isset($multibanco_data->data_limite) && $multibanco_data->data_limite != ''){ ?>
						<tr>
							<td style="font-size: xx-small; color:#dd0000; line-height: 10px; padding:0; border: 0px; text-align:center;" colspan="3"><?php echo $this->__('Data limite de pagamento') ?> : </span><?php echo $multibanco_data->data_limite ?></td>
						</tr>
					<?php } ?>
				</tbody>
			</table>
		</div>
<?php }else{
		echo "<h4>Multibanco</h4>";
		echo $this->__('Os dados para pagamento multibanco serão apresentados quando finalizar a sua encomenda e/ou enviados para o seu e-mail.');
	}?>
		
    </li>
</ul>